name: Benchmark

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21

    - name: Build project
      run: ./gradlew build

    - name: Run benchmark
      run: ./gradlew benchmark

    - name: Commit benchmark results
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        mkdir -p docs
        mv build/benchmark_output/benchmark.png docs/benchmark.png || true

        if ! grep -q '## Benchmark Results' README.md; then
          echo -e '\n## Benchmark Results\n\n![Benchmark](docs/benchmark.png)' >> README.md
        fi

        git add README.md docs/benchmark.png
        git commit -m "Update benchmark results"
        branch=$(git rev-parse --abbrev-ref HEAD)
        git push origin "$branch"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
