name: Benchmark

on:
  push:
    branches:
      - main
  workflow_dispatch: # возможность запускать вручную

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Build project
      run: ./gradlew build

    - name: Run benchmark
      run: ./gradlew benchmark

    - name: Commit benchmark results
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        mkdir -p docs
        cp benchmark.png docs/benchmark.png
        if ! grep -q 'Benchmark Results' README.md; then
          echo '## Benchmark Results\n\n![Benchmark](docs/benchmark.png)' >> README.md
        else
          sed -i '/Benchmark Results/,/\.png/ s|!\[Benchmark\](.*)|![Benchmark](docs/benchmark.png)|' README.md
        fi
        git add README.md docs/benchmark.png
        git commit -m "Update benchmark results"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
