name: Build & Run tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: zulu
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Build (without tests)
        run: ./gradlew assemble

      - name: Run tests
        run: ./gradlew test --stacktrace

      - name: Check formatting
        run: ./gradlew ktlintCheck
